### ISSUE TITLE
Searching with the ampersand symbol "&" produces inaccurate results.

### ISSUE THREAD

**Issue by stayxnegative** [vyonizr/itunes-hd-album-artwork-finder#9]
![Screenshot](https://user-images.githubusercontent.com/29215335/130181018-bf2614fe-050b-42ec-8830-5758434cd2c6.png)

A temporary workaround is type out the word 'and'
![Screenshot2](https://user-images.githubusercontent.com/29215335/130181062-0a1a4190-b2bc-4723-8f80-ff57285904ec.png)

**Comment by vyonizr** [comment]
Apologize for the late response. I've just fixed this issue, thank you.

#12 
#13
